name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

workspace:
  - packages/core_ui_kit

dependencies:
  bloc: ^9.1.0
  connectivity_plus: ^7.0.0
  core_ui_kit: null
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_analytics: ^12.1.0
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.12.0
  flutter_getit: ^3.0.1
  font_awesome_flutter: ^10.12.0
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  get_it: ^7.7.0
  go_router: ^17.0.1
  google_fonts: ^7.0.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  talker: ^5.1.9
  talker_bloc_logger: ^5.1.9
  talker_flutter: ^5.1.9
  toastification: ^3.0.3
  url_launcher: ^6.3.2

dev_dependencies:
  bloc_lint: ^0.3.5
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  faker: ^2.2.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:

  uses-material-design: true

  assets:
    - database/articles/
    - database/articles/content/
    - database/project/
