name: material_design_system
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  gap: ^3.0.1
  material_color_utilities: ^0.11.1

dev_dependencies:
  very_good_analysis: ^5.1.0
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.7.0
